### ISSUE TITLE
README's links to website posts

### ISSUE THREAD

**Issue by akhtars** [cmh2166/geonames-reconcile#7]
Hi Christina, thanks so much for making this service (and valuable documentation) available. Just wanted to mention that the links in the "About" section of the README to the two (really useful!) posts on your site are currently returning 404s due to a trailing slash, e.g., `http://christinaharlow.com/thoughts-on-geospatial-metadata/` doesn't work but `http://christinaharlow.com/thoughts-on-geospatial-metadata` does.

**Comment by cmh2166** [comment]
weird, thanks for letting me know. I have a suspicion as to when those links stopped working, but until now I wasn't event paying attention. 

Thanks!
